### ISSUE TITLE
rename repo name

### ISSUE THREAD

**Issue by geo-yrao** [open-climate-data-science/open-climate-data-science.github.io#5]
- [x] Rename website repository to "open-climate-data-science.github.io" to make it consistent with org name. See reference from [GitHub Page](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) 
- [x] This need also be updated in the `go.ncsu.edu` setting.

**Comment by sheilasaia** [comment]
@geo-yrao is it ok if we rename to `open-climate-data.github.io` so it's consistent with the email? I asked a friend of mine who created a website recently for open hydrology for help with the url name for the website. we have a similar group and respository structure to this one but were able to get repo-name.github.io instead of group-name.github.io/repo-name.github.io. I have a feeling it's something in the settings of the group that I messed up. I'll keep you posted!

**Comment by sheilasaia** [comment]
Figured it out! Repo for the website had to be the same as the group name. The email will have to stay the same...hope that's not too complicated for folks. I will change the go.ncsu.edu link soon.
